steps:
- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Setup build environment
- script: |
    conda config --set always_yes yes --set changeps1 no
    conda info -a
    conda create --name rdkit_build cmake ^
        eigen swig
  displayName: Install dependencies- script: |
    mkdir build && cd build
    call activate rdkit_build
    cmake .. ^
    -G "Visual Studio 15 2017 Win64" ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DRDK_INSTALL_INTREE=ON ^
    -DRDK_INSTALL_STATIC_LIBS=OFF ^
    -DRDK_BUILD_CPP_TESTS=OFF ^
    -DRDK_BUILD_PYTHON_WRAPPERS=OFF ^
    -DRDK_USE_BOOST_REGEX=OFF ^
    -DRDK_BUILD_COORDGEN_SUPPORT=ON ^
    -DRDK_OPTIMIZE_NATIVE=ON ^
    -DRDK_BUILD_TEST_GZIP=ON ^
    -DRDK_BUILD_FREESASA_SUPPORT=OFF ^
    -DRDK_BUILD_AVALON_SUPPORT=ON ^
    -DRDK_BUILD_INCHI_SUPPORT=ON ^
    -DRDK_BUILD_THREADSAFE_SSS=ON ^
    -DRDK_BUILD_SWIG_WRAPPERS=ON ^
    -DRDK_SWIG_STATIC=OFF ^
    -DRDK_TEST_MULTITHREADED=ON 
  displayName: Configure build (Run CMake)
- script: |
    call activate rdkit_build
    cd build
    cmake --build . --config Release --target install -j $(number_of_cores)
  displayName: Build
- script: |
    call activate rdkit_build
    set RDBASE=%cd%
    set PATH=%RDBASE%\lib;%PATH%
    cd build
    ctest -j $(number_of_cores) --output-on-failure -T Test
  displayName: Run tests
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'CTest'
    testResultsFiles: 'build/Testing/*/Test.xml'
    testRunTitle: $(system.phasedisplayname)  CTest Test Run
